### ISSUE TITLE
Add CI coverage for 1.28

### ISSUE THREAD

**Issue by jackfrancis** [Azure/karpenter#6]
### Tell us about your request

Add a ci-test (1.28.x) job to validate unit tests against k8s 1.28.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Yes, we should add 1.28, but first should fix the timeout condition that happens with 1.25, 1.26, 1.27 that causes these ci pipelines to fail. 


then after we fix that timeout condition we can add 1.28 to the matrix

**Comment by Bryce-Soghigian** [comment]
https://github.com/Azure/karpenter/actions/runs/6790866753/job/18461231128?pr=9 referring to these types of runs we see a ton of failing after 10 minutes in our runs, might be worth investigating further

```
PASS
panic: Log in goroutine after TestAzure has completed: 2023-11-07T22:18:44.558Z	ERROR	pricing	pricing/pricing.go:166	error updating on-demand pricing for region , no on-demand pricing found, using existing pricing data from 2023-10-27T06:44:32Z

goroutine 27 [running]:
testing.(*common).logDepth(0xc0007e64e0, {0xc0004a0300, 0xbd}, 0x3)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1022 +0x674
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1004
testing.(*common).Logf(0xc0007e64e0, {0x21e7df6, 0x2}, {0xc0002a01b0, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1055 +0x9a
go.uber.org/zap/zaptest.testingWriter.Write({{0x2520148?, 0xc0007e64e0?}, 0x1?}, {0xc00090e800, 0xbe, 0x400})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zaptest/logger.go:130 +0x11e
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0007c9a70, {0x2, {0xc14acbd12144e29a, 0x82b9dc4, 0x3275560}, {0x21ea1d2, 0x7}, {0xc000814000, 0x7f}, {0x1, ...}, ...}, ...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/core.go:99 +0x193
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005aa1a0, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:253 +0x2b0
go.uber.org/zap.(*SugaredLogger).log(0xc0003540a8, 0x2, {0x225c39c, 0x57}, {0xc0008eefa0, 0x3, 0x3}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:316 +0x130
go.uber.org/zap.(*SugaredLogger).Errorf(0xc00004ae28?, {0x225c39c, 0x57}, {0xc0008eefa0, 0x3, 0x3})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/sugar.go:189 +0x85
github.com/Azure/karpenter/pkg/providers/pricing.(*Provider).updatePricing.func1()
	/home/runner/work/karpenter/karpenter/pkg/providers/pricing/pricing.go:166 +0x26d
created by github.com/Azure/karpenter/pkg/providers/pricing.(*Provider).updatePricing in goroutine 173
	/home/runner/work/karpenter/karpenter/pkg/providers/pricing/pricing.go:163 +0x1a5
ginkgo run failed
  could not finalize profiles:
  Unable to read coverage file /home/runner/work/karpenter/karpenter/pkg_providers_pricing_coverage.out:
  open /home/runner/work/karpenter/karpenter/pkg_providers_pricing_coverage.out: no such file or directory
make: *** [Makefile:31: battletest] Error 1
Error: Process completed with exit code 2.
```

**Comment by tallaxes** [comment]
Fixed in https://github.com/Azure/karpenter/pull/31
